directories:
  output: dist-electron
  buildResources: build
appId: com.chubut.trivia
productName: Trivia
files:
  - filter:
      - dist/browser/**/*
      - main.js
      - package.json
win:
  target:
    - nsis
  forceCodeSigning: false
  icon: icono.ico
mac: null
linux: null
electronVersion: 38.1.0
